sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-eu-central-1.aliyuncs.com
    access-key-id: LTAI5tCzgdo9Rh7hzYucFRyQ
    access-key-secret: L8pZqDpIPDCnebIUtTZRnZThUca55F
    bucket-name: sky-take-out-bucket01
  redis:
    host: localhost
    port: 6379
