sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-eu-central-1.aliyuncs.com
    access-key-id: LTAI5tCzgdo9Rh7hzYucFRyQ
    access-key-secret: L8pZqDpIPDCnebIUtTZRnZThUca55F
    bucket-name: sky-take-out-bucket01
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxbd19f79f42b49198
    secret: 5f38a8de28ebb9fd9247c76e84361939
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://4e0f7e29.r21.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://4e0f7e29.r21.cpolar.top/notify/refundSuccess